"""Tier 2: convert integration tests — invoke the real pandoc binary.

These tests exercise `pandoc-cli convert to ...` end-to-end via Typer's
`CliRunner`, write to `tmp_path`, and verify outputs with the format-magic
helpers from `qa/pandoc/conftest.py`.

Tests that need a LaTeX PDF engine consume the `latex_engine` fixture so they
skip cleanly on machines without one.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

from _pandoc_helpers import (
    assert_docx_magic,
    assert_epub_magic,
    assert_html_doctype,
    assert_pdf_magic,
)


pytestmark = pytest.mark.integration


@pytest.fixture
def runner() -> CliRunner:
    # mix_stderr defaults to True in older Click versions, False in newer ones.
    # We want stderr separate so we can assert on error messages without
    # polluting stdout assertions.
    try:
        return CliRunner(mix_stderr=False)
    except TypeError:
        # Newer Click drops the kwarg (stderr is always separate).
        return CliRunner()


@pytest.fixture
def app(pandoc_path):
    """Import the Typer app — depends on pandoc_path so we skip cleanly when
    pandoc isn't installed."""
    from pandoc_cli import app as _app

    return _app


# ---------------------------------------------------------------------------
# Happy paths — one per output format
# ---------------------------------------------------------------------------


class TestConvertHtml:
    def test_html_output_has_doctype(self, runner, app, simple_md, tmp_path):
        out = tmp_path / "out.html"
        result = runner.invoke(
            app,
            ["convert", "to", str(simple_md), str(out), "--standalone"],
        )
        assert result.exit_code == 0, result.output
        assert_html_doctype(out)

    def test_no_standalone_emits_fragment(self, runner, app, simple_md, tmp_path):
        """``--no-standalone`` must produce a fragment with NO <!DOCTYPE> or
        <html> wrapper — just the body content."""
        out = tmp_path / "frag.html"
        result = runner.invoke(
            app,
            ["convert", "to", str(simple_md), str(out), "--no-standalone"],
        )
        assert result.exit_code == 0, result.output
        text = out.read_text(encoding="utf-8")
        assert "<!DOCTYPE" not in text and "<!doctype" not in text
        assert "<html" not in text.lower()
        # Body content should still be present.
        assert "<h1" in text


class TestConvertEmbedResources:
    def test_embed_resources_inlines_image_as_data_uri(
        self, runner, app, tmp_path
    ):
        """``--embed-resources`` must inline referenced images as ``data:``
        URIs instead of leaving an external ``<img src="path">`` reference.

        We reference the image with an absolute path so pandoc can find it
        regardless of the subprocess cwd (pandoc resolves relative image
        paths against its own working directory, not the markdown's dir,
        unless ``--resource-path`` is set)."""
        # 1x1 transparent PNG.
        png_bytes = bytes.fromhex(
            "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4"
            "890000000d49444154789c63000100000005000100"
            "0d0a2db40000000049454e44ae426082"
        )
        img = tmp_path / "pixel.png"
        img.write_bytes(png_bytes)

        src = tmp_path / "with_img.md"
        # Markdown image syntax with parens needs URL-encoding of spaces; the
        # tmp_path here is generated by pytest and shouldn't contain any.
        src.write_text(
            f"# Pic\n\n![alt]({img.as_posix()})\n",
            encoding="utf-8",
        )
        out = tmp_path / "out.html"

        result = runner.invoke(
            app,
            [
                "convert",
                "to",
                str(src),
                str(out),
                "--standalone",
                "--embed-resources",
            ],
        )
        assert result.exit_code == 0, result.output
        text = out.read_text(encoding="utf-8")
        # Inlined PNG appears as data:image/png;base64,...
        assert "data:image/png;base64," in text, (
            "expected data: URI for embedded PNG; got plain src reference"
        )
        # And the raw filename should NOT appear as the src= value.
        assert f'src="{img.as_posix()}"' not in text


class TestConvertDocx:
    def test_docx_has_zip_header(self, runner, app, simple_md, tmp_path):
        """Verify the output is not just any ZIP (which would also accept
        EPUB/JAR/raw zip) but a real DOCX — the OOXML package always contains
        ``word/document.xml`` at the top of the namelist."""
        import zipfile

        out = tmp_path / "out.docx"
        result = runner.invoke(
            app,
            ["convert", "to", str(simple_md), str(out)],
        )
        assert result.exit_code == 0, result.output
        assert_docx_magic(out)

        with zipfile.ZipFile(out) as zf:
            names = zf.namelist()
        assert "word/document.xml" in names, (
            f"DOCX must contain word/document.xml; namelist was: {names[:10]}"
        )


class TestConvertEpub:
    def test_epub_has_mimetype(self, runner, app, simple_md, tmp_path):
        out = tmp_path / "out.epub"
        result = runner.invoke(
            app,
            ["convert", "to", str(simple_md), str(out)],
        )
        assert result.exit_code == 0, result.output
        assert_epub_magic(out)


class TestConvertLatex:
    def test_latex_text_contains_begin_document(self, runner, app, simple_md, tmp_path):
        out = tmp_path / "out.tex"
        result = runner.invoke(
            app,
            ["convert", "to", str(simple_md), str(out), "--standalone"],
        )
        assert result.exit_code == 0, result.output
        text = out.read_text(encoding="utf-8")
        assert "\\begin{document}" in text
        assert "\\end{document}" in text


class TestConvertPdf:
    def test_pdf_has_magic(self, runner, app, simple_md, tmp_path, latex_engine):
        out = tmp_path / "out.pdf"
        result = runner.invoke(
            app,
            ["convert", "to", str(simple_md), str(out), "--pdf-engine", latex_engine],
        )
        assert result.exit_code == 0, result.output
        assert_pdf_magic(out)

    def test_pdf_path_with_spaces(self, runner, app, simple_md, tmp_path, latex_engine):
        out_dir = tmp_path / "dir with spaces"
        out_dir.mkdir()
        out = out_dir / "my output.pdf"
        result = runner.invoke(
            app,
            ["convert", "to", str(simple_md), str(out), "--pdf-engine", latex_engine],
        )
        assert result.exit_code == 0, result.output
        assert_pdf_magic(out)


# ---------------------------------------------------------------------------
# Error / edge cases
# ---------------------------------------------------------------------------


class TestConvertErrors:
    def test_missing_input_exits_one_with_clear_message(self, runner, app, tmp_path):
        bogus = tmp_path / "nope.md"
        out = tmp_path / "out.html"
        result = runner.invoke(
            app,
            ["convert", "to", str(bogus), str(out)],
        )
        assert result.exit_code == 1
        # Error appears either on stderr (preferred) or merged output.
        combined = (result.stderr or "") + (result.output or "")
        assert "Input file not found" in combined
        assert not out.exists()

    def test_pdf_with_no_engine_exits_one(
        self, runner, app, simple_md, tmp_path, monkeypatch
    ):
        """Force find_pdf_engines to return [] and verify clean exit + message,
        without attempting any LaTeX run."""
        from pandoc_cli.commands import convert_to

        monkeypatch.setattr(convert_to, "find_pdf_engines", lambda: [])
        out = tmp_path / "out.pdf"
        result = runner.invoke(
            app,
            ["convert", "to", str(simple_md), str(out)],
        )
        assert result.exit_code == 1
        combined = (result.stderr or "") + (result.output or "")
        assert "PDF" in combined
        assert "engine" in combined.lower()


class TestConvertStdout:
    def test_stdout_output_for_text_format(self, runner, app, simple_md):
        """`-` as output should write the text format to stdout."""
        result = runner.invoke(
            app,
            ["convert", "to", str(simple_md), "-", "--to", "html"],
        )
        assert result.exit_code == 0, result.stderr or result.output
        # Output should contain at least one HTML tag from our markdown body.
        assert "<h1" in result.stdout or "<h1" in result.output


# ---------------------------------------------------------------------------
# Frontmatter-vs-CLI metadata: CLI wins (gotchas.md)
# ---------------------------------------------------------------------------


class TestConvertMetadataPriority:
    def test_cli_metadata_overrides_frontmatter_title(
        self, runner, app, md_with_frontmatter, tmp_path
    ):
        """``--metadata title=Override`` must win over the YAML frontmatter
        ``title: Sample Document`` and end up as the ACTIVE <title> element —
        not just appear somewhere in the document body or metadata block."""
        import re

        out = tmp_path / "out.html"
        result = runner.invoke(
            app,
            [
                "convert",
                "to",
                str(md_with_frontmatter),
                str(out),
                "--standalone",
                "--metadata",
                "title=Override",
            ],
        )
        assert result.exit_code == 0, result.output
        assert_html_doctype(out)
        text = out.read_text(encoding="utf-8")

        # The CLI override must be the actual <title>...</title> element.
        match = re.search(r"<title>(.*?)</title>", text, flags=re.DOTALL)
        assert match is not None, "no <title> element in output HTML"
        title_text = match.group(1).strip()
        assert "Override" in title_text, (
            f"CLI override should be inside <title>; got <title>{title_text!r}</title>"
        )
        # And the frontmatter value must NOT be the active <title>.
        assert "Sample Document" not in title_text, (
            "frontmatter title leaked into <title>; CLI --metadata did not win"
        )
